# Generated by Django 3.2.5 on 2021-07-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alimento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_peluqueria',
            fields=[
                ('idProducto_peluqueria', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_peluqueria', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
            options={
                'verbose_name': 'producto_peluqueria',
                'verbose_name_plural': 'productos_peluqueria',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Producto_limpieza',
            fields=[
                ('idProducto_limpieza', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_limpieza', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
            options={
                'verbose_name': 'producto_limpieza',
                'verbose_name_plural': 'productos_limpieza',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('idAccesorio', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Stock')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='accesorios', verbose_name='Imagen')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
            options={
                'verbose_name': 'accesorio',
                'verbose_name_plural': 'accesorios',
                'ordering': ['descripcion'],
            },
        ),
    ]
