# Generated by Django 3.2.5 on 2021-07-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_alimento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alimentos', verbose_name='Imagen'),
        ),
    ]
